// gen-segdefs reads visual6502/segdefs.js and emits
// ui/visualcpuwin/segdefs.go. One-shot — run when the upstream
// data changes (rarely; the 6502 isn't going to grow new
// transistors). The generated file is committed and used directly
// at runtime; we don't generate at build time.
//
// Usage:
//
//	go run ./tools/gen-segdefs \
//	  -src ../visual6502/segdefs.js \
//	  -out ui/visualcpuwin/segdefs.go
package main

import (
	"bufio"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func main() {
	srcPath := flag.String("src", "../visual6502/segdefs.js",
		"path to visual6502 segdefs.js")
	outPath := flag.String("out", "ui/visualcpuwin/segdefs.go",
		"path to generated Go file")
	flag.Parse()

	in, err := os.Open(*srcPath)
	if err != nil {
		log.Fatalf("open %s: %v", *srcPath, err)
	}
	defer in.Close()

	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		log.Fatalf("mkdir: %v", err)
	}
	out, err := os.Create(*outPath)
	if err != nil {
		log.Fatalf("create %s: %v", *outPath, err)
	}
	defer out.Close()

	w := bufio.NewWriter(out)
	defer w.Flush()

	fmt.Fprintln(w, "// Code generated by tools/gen-segdefs. DO NOT EDIT.")
	fmt.Fprintln(w, "// Source: visual6502/segdefs.js")
	fmt.Fprintln(w, "// License: CC BY-NC-SA 3.0 (per upstream)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "package visualcpuwin")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// Segments is the polygon table for the MOS 6502 die layout.")
	fmt.Fprintln(w, "// Each entry: one filled polygon belonging to one node, on one")
	fmt.Fprintln(w, "// silicon layer. Coords are the original visual6502 chip-space")
	fmt.Fprintln(w, "// (un-normalised; the renderer scales to fit the canvas).")
	fmt.Fprintln(w, "var Segments = []Segment{")

	// segdefs lines look like:
	//   [   0,'+',1,5391,8260,5391,8216,5357,8216,5357,8260],
	re := regexp.MustCompile(`^\[\s*(\d+)\s*,\s*'([+\-])'\s*,\s*(\d+)\s*,(.+?)\]\s*,?\s*$`)

	count := 0
	s := bufio.NewScanner(in)
	s.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for s.Scan() {
		line := strings.TrimSpace(s.Text())
		if !strings.HasPrefix(line, "[") {
			continue
		}
		m := re.FindStringSubmatch(line)
		if m == nil {
			log.Printf("WARN: unparsed line: %s", line)
			continue
		}
		nodeID := m[1]
		pull := m[2]
		layer := m[3]
		coordsRaw := strings.TrimSpace(m[4])

		// Clean coords list — drop empties so trailing-comma cases work.
		var coords []string
		for _, c := range strings.Split(coordsRaw, ",") {
			c = strings.TrimSpace(c)
			if c == "" {
				continue
			}
			coords = append(coords, c)
		}

		pullUp := "false"
		if pull == "+" {
			pullUp = "true"
		}

		fmt.Fprintf(w, "\t{%s, %s, %s, []int32{%s}},\n",
			nodeID, pullUp, layer, strings.Join(coords, ", "))
		count++
	}
	if err := s.Err(); err != nil {
		log.Fatalf("scan: %v", err)
	}
	fmt.Fprintln(w, "}")

	log.Printf("wrote %d segments to %s", count, *outPath)
}
